version: '3'
services:
    homeassistant:
        container_name: home-assistant
        image: homeassistant/home-assistant:stable
        volumes:
            - $PWD/home-assistant/config:/config
            - /mnt/media:/media/nas
        environment:
            - TZ=America/Chicago
        restart: unless-stopped
        network_mode: host

    homebridge:
        container_name: homebridge
        image: oznu/homebridge:latest
        network_mode: host
        environment:
            HOMEBRIDGE_CONFIG_UI: '1'
            HOMEBRIDGE_CONFIG_UI_PORT: '8090'
            PGUID: '1000'
            PUID: '1000'
            TZ: America/Chicago
        volumes:
            - $PWD/homebridge/config:/homebridge:rw
        restart: unless-stopped

    node-red:
        image: nodered/node-red
        container_name: node-red
        network_mode: host
        env_file:
            -   $PWD/node-red/data/.env
        volumes:
            - $PWD/node-red/data:/data
        restart: unless-stopped

    mqtt:
        image: eclipse-mosquitto
        container_name: mqtt
        ports:
            - 8383:8383
            - 9001:9001
        volumes:
            - $PWD/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - $PWD/mqtt/data:/mosquitto/data
            - $PWD/mqtt/log:/mosquitto/log
        restart: unless-stopped


    papermerge:
        image: ghcr.io/linuxserver/papermerge
        container_name: papermerge
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
            # - REDIS_URL= #optional
        volumes:
            - $PWD/papermerge/appdata/config:/config
            - /mnt/filestore/papermerge:/data
        ports:
            - 8000:8000
        restart: unless-stopped

    makemkv:
        image: jlesage/makemkv
        container_name: makemkv
        network_mode: host
        environment:
           - PUID=1000
           - PGID=1000
        ports:
            - 5800:5800
        volumes:
            - $PWD/makemkv/appdata:/config:rw
            - $HOME:/storage:ro
            - /mnt/media/ingest:/output:rw
        devices:
            - /dev/sr0:/dev/sr0
            - /dev/sg0:/dev/sg0
        restart: always

    plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
        volumes:
            - $PWD/plex/config:/config
            - /mnt/media:/media
        restart: always

    tautulli:
        image: linuxserver/tautulli
        container_name: tautulli
        ports:
            - 8181:8181
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - $PWD/tautulli/config:/config
            - $PWD/plex/config/Library/Application Support/Plex Media Server/Logs:/logs
        restart: unless-stopped

