# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.139

binary_sensor:
  - platform: ping
    host: 1.1.1.1
    name: "Cloudflare DNS Check"
    count: 2
    scan_interval: 15

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: Twilio SMS Notifier
    platform: twilio_sms
    from_number: +16023629258

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
