# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
    - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
    - platform: yamaha_musiccast
      host: 192.168.1.139

binary_sensor:
    - platform: ping
      host: 1.1.1.1
      name: "Cloudflare DNS Check"
      count: 2
      scan_interval: 15

sensor:
    - platform: nut
      name: TRIPP LITE UPS
      host: 192.168.1.67
      resources: 
        - ups.status
        - ups.load
        - ups.power
        - input.voltage
        - battery.charge
        - battery.runtime
        - battery.voltage
        - output.voltage